/* PhysiX Academy — Quiz Bank Part A: Levels 1 & 2 */
'use strict';

/* Question shape: {id, topic, difficulty, q, choices[4], answer(index), why} */
const QUIZ_BANK = [];

QUIZ_BANK.push(
  { id:'q-v1', topic:'vectors', difficulty:'beginner',
    q:'Which of these is a vector quantity?',
    choices:['Speed','Mass','Velocity','Temperature'], answer:2,
    why:'Velocity includes direction (e.g. 20 m/s north). Speed, mass and temperature are scalars.' },
  { id:'q-v2', topic:'vectors', difficulty:'intermediate',
    q:'A 100 N force acts at 60\u00b0 above the horizontal. Its vertical component is closest to:',
    choices:['50 N','86.6 N','100 N','60 N'], answer:1,
    why:'$F_y = F\\sin\\theta = 100\\sin60\\degree \\approx 86.6$ N.' },
  { id:'q-v3', topic:'vectors', difficulty:'advanced',
    q:'Two forces of 3 N and 4 N act at right angles. Their resultant is:',
    choices:['7 N','1 N','5 N','12 N'], answer:2,
    why:'Perpendicular vectors add by Pythagoras: $\\sqrt{3^2+4^2}=5$ N.' },

  { id:'q-ma1', topic:'math', difficulty:'beginner',
    q:'On a distance\u2013time graph, the slope represents:',
    choices:['Acceleration','Speed','Distance','Force'], answer:1,
    why:'Slope = rise/run = distance/time = speed.' },
  { id:'q-ma2', topic:'math', difficulty:'intermediate',
    q:'Rearranging $KE=\\tfrac12 mv^2$ for $v$ gives:',
    choices:['$v=2KE/m$','$v=\\sqrt{2KE/m}$','$v=\\sqrt{KE/2m}$','$v=(2KE/m)^2$'], answer:1,
    why:'Multiply by 2, divide by m, then square-root.' },

  { id:'q-k1', topic:'kinematics', difficulty:'beginner',
    q:'The SI unit of acceleration is:',
    choices:['m/s','m/s\u00b2','N','m'], answer:1,
    why:'(m/s) per second = m/s\u00b2.' },
  { id:'q-k2', topic:'kinematics', difficulty:'beginner',
    q:'A car goes from rest to 20 m/s in 5 s. Average acceleration:',
    choices:['4 m/s\u00b2','100 m/s\u00b2','0.25 m/s\u00b2','25 m/s\u00b2'], answer:0,
    why:'$a=(v-u)/t=(20-0)/5=4$ m/s\u00b2.' },
  { id:'q-k3', topic:'kinematics', difficulty:'intermediate',
    q:'On a distance\u2013time graph a flat horizontal line means the object is:',
    choices:['At constant speed','Accelerating','At rest','Moving backwards'], answer:2,
    why:'Zero slope means distance is not changing: stationary.' },
  { id:'q-k4', topic:'kinematics', difficulty:'advanced',
    q:'In projectile motion (no air resistance), the horizontal velocity component is:',
    choices:['Zero','Constant','Increasing','Decreasing'], answer:1,
    why:'No horizontal force acts, so $v_x=u\\cos\\theta$ stays constant while gravity acts only vertically.' },
  { id:'q-k5', topic:'kinematics', difficulty:'expert',
    q:'For fixed launch speed, maximum range on level ground occurs at:',
    choices:['30\u00b0','45\u00b0','60\u00b0','90\u00b0'], answer:1,
    why:'Range $R=u^2\\sin2\\theta/g$ peaks when $2\\theta=90\\degree$, i.e. 45\u00b0.' },
  { id:'q-k6', topic:'kinematics', difficulty:'intermediate',
    q:'Area under a speed\u2013time graph gives:',
    choices:['Acceleration','Distance travelled','Average speed','Force'], answer:1,
    why:'Speed \u00d7 time accumulates distance \u2014 the area under the curve.' },

  { id:'q-f1', topic:'newton', difficulty:'beginner',
    q:"Newton's First Law is also called the law of:",
    choices:['Gravity','Inertia','Momentum','Energy'], answer:1,
    why:'Objects keep their state unless a net force acts \u2014 resistance to change is inertia.' },
  { id:'q-f2', topic:'newton', difficulty:'intermediate',
    q:'Net force needed to accelerate 10 kg at 5 m/s\u00b2:',
    choices:['2 N','50 N','15 N','0.5 N'], answer:1,
    why:'$F=ma=10\\times5=50$ N.' },
  { id:'q-f3', topic:'friction', difficulty:'intermediate',
    q:'Friction on a sliding box points:',
    choices:['Along the motion','Opposite to sliding','Downward','Perpendicular to surface'], answer:1,
    why:'Friction opposes relative sliding; magnitude $f=\\mu N$.' },
  { id:'q-f4', topic:'newton', difficulty:'advanced',
    q:"Action\u2013reaction pairs never cancel because they:",
    choices:['Differ in size','Act on different objects','Point the same way','Are not real forces'], answer:1,
    why:'Third-law pairs act on DIFFERENT bodies, so no single body feels both.' },

  { id:'q-e1', topic:'energy', difficulty:'beginner',
    q:'Kinetic energy depends on speed as:',
    choices:['KE \u221d v','KE \u221d v\u00b2','KE \u221d 1/v','KE \u221d \u221av'], answer:1,
    why:'$KE=\\tfrac12 mv^2$ \u2014 doubling speed quadruples KE.' },
  { id:'q-e2', topic:'energy', difficulty:'intermediate',
    q:'If a car doubles its speed, braking distance becomes roughly:',
    choices:['2\u00d7','4\u00d7','Same','Half'], answer:1,
    why:'Brakes remove KE \u221d v\u00b2, so four times the stopping distance.' },
  { id:'q-e3', topic:'energy', difficulty:'intermediate',
    q:'PE of a 5 kg book on a 10 m shelf (g = 9.8):',
    choices:['50 J','98 J','245 J','490 J'], answer:3,
    why:'$PE=mgh=5\\times9.8\\times10=490$ J.' },
  { id:'q-e4', topic:'energy', difficulty:'advanced',
    q:'Work done by your upward force while carrying a bag horizontally at constant velocity:',
    choices:['Large positive','Negative','Zero','Equal to $mgd$'], answer:2,
    why:'$W=Fd\\cos90\\degree=0$: force is perpendicular to displacement.' },

  { id:'q-p1', topic:'momentum', difficulty:'beginner',
    q:'Linear momentum equals:',
    choices:['mass \u00d7 acceleration','mass \u00d7 velocity','force \u00d7 distance','energy \u00d7 time'], answer:1,
    why:'$p=mv$, a vector along the velocity.' },
  { id:'q-p2', topic:'momentum', difficulty:'intermediate',
    q:'Airbags protect mainly by:',
    choices:['Reducing \u0394p','Stretching collision time to cut force','Adding force','Reducing mass'], answer:1,
    why:'Impulse $F\\Delta t=\\Delta p$: bigger \u0394t means smaller average F.' },
  { id:'q-p3', topic:'momentum', difficulty:'advanced',
    q:'In ALL collisions, what is always conserved?',
    choices:['KE only','Momentum only','Both always','Neither'], answer:1,
    why:'Momentum survives without external forces; sticking collisions lose KE.' },

  { id:'q-g1', topic:'gravity', difficulty:'beginner',
    q:'An astronaut travels to the Moon. Which stays the same?',
    choices:['Weight','Mass','Both','Neither'], answer:1,
    why:'Mass is intrinsic; weight $=mg$ shrinks with local g.' },
  { id:'q-g2', topic:'gravity', difficulty:'intermediate',
    q:'Astronauts float in the ISS because:',
    choices:['No gravity up there','They are in continuous free fall','No air','They are massless'], answer:1,
    why:'Gravity there is ~89% of surface strength; orbiting IS perpetual falling around Earth.' },

  { id:'q-h1', topic:'heat', difficulty:'beginner',
    q:'Heat naturally flows:',
    choices:['Cold to hot','Hot to cold','Both equally','Only in metals'], answer:1,
    why:'Spontaneous transfer goes from higher to lower temperature.' },
  { id:'q-h2', topic:'heat', difficulty:'intermediate',
    q:'Water moderates coastal climates because its specific heat is:',
    choices:['Very small','Very large','Zero','Same as sand'], answer:1,
    why:"$Q=mc\\Delta T$: water's huge c means it warms/cools slowly, buffering temperature swings." },

  { id:'q-w1', topic:'waves', difficulty:'beginner',
    q:'The wave equation relating speed, frequency and wavelength is:',
    choices:['$v=f/\\lambda$','$v=f\\lambda$','$v=\\lambda/f$','$f=v\\lambda$'], answer:1,
    why:'$v=f\\lambda$ holds for all waves.' },
  { id:'q-w2', topic:'waves', difficulty:'intermediate',
    q:'Sound cannot travel through space because sound is:',
    choices:['Transverse','A mechanical wave needing a medium','Electromagnetic','Too fast'], answer:1,
    why:'Longitudinal mechanical waves require matter to oscillate; vacuum has none.' },

  { id:'q-el1', topic:'electricity', difficulty:'beginner',
    q:'With V = 12 V across R = 6 \u03a9, current is:',
    choices:['0.5 A','2 A','72 A','6 A'], answer:1,
    why:"Ohm's law: $I=V/R=12/6=2$ A." },
  { id:'q-el2', topic:'electricity', difficulty:'intermediate',
    q:'Wires overheat mainly because of which power loss?',
    choices:['$V/R$','$I^2R$','$V^2/I$','$IR/V$'], answer:1,
    why:'Resistive heating $P=I^2R$ grows with the square of current.' },
  { id:'q-el3', topic:'electricity', difficulty:'advanced',
    q:'In a series circuit, what is the SAME through every element?',
    choices:['Voltage','Current','Resistance','Power'], answer:1,
    why:'One path: charge flow is common. Voltage divides; in parallel it flips (same V, shared I).' },

  { id:'q-mag1', topic:'magnetism', difficulty:'beginner',
    q:'Two north poles brought together will:',
    choices:['Attract','Repel','Nothing','Merge'], answer:1,
    why:'Like poles repel; unlike attract.' },
  { id:'q-mag2', topic:'magnetism', difficulty:'intermediate',
    q:'A stationary electric charge produces:',
    choices:['Magnetic field','Electric field only','Both fields','Neither'], answer:1,
    why:'Only MOVING charges create magnetic fields (\u00d8rsted); static charge makes E alone.' },

  { id:'q-li1', topic:'light', difficulty:'beginner',
    q:'The speed of light in vacuum is about:',
    choices:['340 m/s','$3\\times10^8$ m/s','$3\\times10^6$ m/s','Infinite'], answer:1,
    why:'$c=3\\times10^8$ m/s \u2014 the universal speed limit.' },
  { id:'q-li2', topic:'light', difficulty:'intermediate',
    q:'Light bends when entering water because its:',
    choices:['Frequency changes','Speed changes','Colour changes','Energy vanishes'], answer:1,
    why:'Refraction comes from speed change between media; frequency stays fixed.' }
);
