/* PhysiX Academy — Quiz Bank Part C: Level 3 (E&M, Optics, Modern) + Level 4 */
'use strict';

QUIZ_BANK.push(
  { id:'q-ch1', topic:'charges', difficulty:'intermediate',
    q:'Doubling the distance between two point charges changes the force to:',
    choices:['Half','Quarter','Double','Same'], answer:1,
    why:'$F\\propto 1/r^2$: double r means $1/4$ the force.' },
  { id:'q-ch2', topic:'charges', difficulty:'advanced',
    q:'Electric field lines never cross because:',
    choices:['They repel each other','E has one unique direction at any point','Charges block them','It is only a drawing rule'], answer:1,
    why:'A test charge feels ONE net force; crossing lines would imply two directions at once.' },

  { id:'q-pc1', topic:'potential', difficulty:'intermediate',
    q:'Energy stored in capacitor C charged to V is:',
    choices:['$CV$','$\\tfrac12 CV$','$\\tfrac12 CV^2$','$C^2V$'], answer:2,
    why:'$U=\\tfrac12 CV^2$ \u2014 why flash capacitors specify both C and voltage rating.' },
  { id:'q-pc2', topic:'potential', difficulty:'advanced',
    q:'Two identical capacitors in PARALLEL give total capacitance:',
    choices:['Half of one','Same','Twice one','Zero'], answer:2,
    why:'Parallel capacitances add directly (opposite of resistors).' },

  { id:'q-cr1', topic:'current', difficulty:'beginner',
    q:'Drift velocity of electrons in household wires is roughly:',
    choices:['Near light speed','~1000 m/s','Fractions of a mm per second','Zero always'], answer:2,
    why:'Electrons creep slowly; the FIELD propagates near light speed, which is why lights turn on instantly.' },
  { id:'q-cr2', topic:'current', difficulty:'advanced',
    q:'6 \u03a9 and 3 \u03a9 resistors in parallel give equivalent:',
    choices:['9 \u03a9','2 \u03a9','18 \u03a9','4.5 \u03a9'], answer:1,
    why:'$1/R=1/6+1/3=1/2$ \u21d2 2 \u03a9, below the smallest branch.' },

  { id:'q-mv1', topic:'magforce', difficulty:'intermediate',
    q:'The magnetic force on a charge does no work because it is always:',
    choices:['Parallel to velocity','Perpendicular to velocity','Zero','Downward'], answer:1,
    why:'$F=qvB\\sin\\theta \\perp v$: direction changes, speed (and KE) do not.' },
  { id:'q-mv2', topic:'magforce', difficulty:'expert',
    q:'A proton enters uniform B along the field direction. Its path is:',
    choices:['Circle','Straight line','Helix','Parabola'], answer:1,
    why:'$F=qvB\\sin0=0$: motion parallel to B feels no force.' },

  { id:'q-mm1', topic:'magnetism', difficulty:'advanced',
    q:'Heating iron past its Curie temperature causes it to:',
    choices:['Become stronger magnet','Lose permanent magnetism','Gain north-only poles','Freeze'], answer:1,
    why:'Thermal agitation destroys domain alignment above ~770\u00b0C.' },

  { id:'q-em1', topic:'em-induction', difficulty:'intermediate',
    q:"Faraday's law: induced EMF is proportional to:",
    choices:['Flux itself','Rate of CHANGE of flux','Current','Resistance'], answer:1,
    why:'$\\varepsilon=-N\\,d\\Phi/dt$: constant flux induces nothing.' },
  { id:'q-em2', topic:'em-induction', difficulty:'advanced',
    q:"Lenz's law minus sign expresses:",
    choices:["Ohm's law","Opposition to flux change (energy conservation)","Gravity","Charge quantisation"], answer:1,
    why:'Induced effects oppose their cause; otherwise perpetual free energy would exist.' },

  { id:'q-ac1', topic:'ac', difficulty:'intermediate',
    q:'Mains labelled 230 V rms actually peaks near:',
    choices:['230 V','325 V','115 V','460 V'], answer:1,
    why:'$V_0=V_{rms}\\sqrt2\\approx230\\times1.414\\approx325$ V.' },
  { id:'q-ac2', topic:'ac', difficulty:'advanced',
    q:'At resonance in an RLC circuit, impedance equals:',
    choices:['Maximum','$R$ only','$X_L+X_C$','Zero always'], answer:1,
    why:'$X_L=X_C$ cancel, leaving pure resistance R and current peak.' },

  { id:'q-ro1', topic:'optics', difficulty:'intermediate',
    q:'Object 30 cm before a converging lens f = +10 cm gives image at:',
    choices:['+7.5 cm','+15 cm','\u221215 cm','+30 cm'], answer:1,
    why:'$1/v=1/f+1/u=1/10\u22121/30=2/30$ \u21d2 v=+15 cm (real, inverted).' },
  { id:'q-ro2', topic:'optics', difficulty:'advanced',
    q:'Light travelling from glass (n=1.5) to air hits at 45\u00b0. Critical angle for glass-air is about 42\u00b0. What happens?',
    choices:['Refracts away from normal','Total internal reflection','Absorbed','Speeds up through'], answer:1,
    why:'Beyond critical angle all light reflects back inside \u2014 fibre optics in action.' },

  { id:'q-wo1', topic:'waveoptics', difficulty:'intermediate',
    q:"Young's double-slit fringes get WIDER when:",
    choices:['Slits move closer together','Screen moves closer','Wavelength decreases','Slit width grows'], answer:0,
    why:'$\\beta=\\lambda D/d$: smaller d (or bigger \u03bb or D) widens spacing.' },
  { id:'q-wo2', topic:'waveoptics', difficulty:'advanced',
    q:'Soap-bubble colours are explained by:',
    choices:['Refraction','Thin-film interference','Polarisation','Dispersion only'], answer:1,
    why:'Reflections from the film\u2019s two surfaces interfere; thickness picks surviving colours.' },

  { id:'q-dn1', topic:'modern', difficulty:'intermediate',
    q:'In the photoelectric effect, brighter light BELOW threshold frequency ejects:',
    choices:['Faster electrons','More electrons','No electrons','Slower electrons'], answer:2,
    why:'Each photon needs $hf\\ge\\phi$. Intensity cannot compensate insufficient photon energy.' },
  { id:'q-dn2', topic:'modern', difficulty:'advanced',
    q:'Photon wavelength 620 nm carries energy closest to:',
    choices:['2 eV','5 eV','10 eV','0.5 eV'], answer:0,
    why:'Shortcut $E(\\text{eV})\\approx1240/\\lambda(\\text{nm})=1240/620=2$ eV.' },

  { id:'q-at1', topic:'atoms', difficulty:'intermediate',
    q:'Ground-state hydrogen energy is \u221213.6 eV. Ionising it from ground requires:',
    choices:['3.4 eV','10.2 eV','13.6 eV','27.2 eV'], answer:2,
    why:'From \u221213.6 eV up to 0 needs exactly 13.6 eV.' },
  { id:'q-at2', topic:'atoms', difficulty:'advanced',
    q:'The n=3\u21922 hydrogen transition emits the red H-alpha line because the photon energy:',
    choices:['Equals level gap 1.89 eV','Equals kinetic energy','Is arbitrary','Comes from nucleus'], answer:0,
    why:'$h\\nu=E_3\u2212E_2=1.89$ eV \u2192 \u03bb\u2248656 nm.' },

  { id:'q-nu1', topic:'nucleus', difficulty:'advanced',
    q:'A sample with 25% of its C-14 remaining (\u00bd life 5730 y) is about:',
    choices:['2865 y old','5730 y old','11460 y old','17190 y old'], answer:2,
    why:'Two halvings (100\u219250\u219225%) \u00d7 5730 years.' },
  { id:'q-nu2', topic:'nucleus', difficulty:'expert',
    q:'Mass defect times c\u00b2 equals:',
    choices:['Kinetic energy','Binding energy','Photon number','Half-life'], answer:1,
    why:'Missing nucleon mass was released as binding energy holding the nucleus together.' },

  { id:'q-se1', topic:'semiconductor', difficulty:'intermediate',
    q:'Doping silicon with phosphorus (5 valence electrons) creates:',
    choices:['p-type','n-type','Insulator','Superconductor'], answer:1,
    why:'Extra electron donors \u21d2 n-type. Trivalent dopants like boron give p-type.' },
  { id:'q-se2', topic:'semiconductor', difficulty:'advanced',
    q:'A forward-biased silicon diode begins conducting around:',
    choices:['0 V','0.7 V','5 V','Reverse breakdown'], answer:1,
    why:'Junction barrier \u22480.7 V must be overcome; reversed, it blocks.' },

  { id:'q-sr1', topic:'relativity', difficulty:'expert',
    q:'Moving clocks run slow by factor \u03b3. A muon with \u03b3=22 lives (lab frame) how much longer than its proper 2.2 \u03bcs?',
    choices:['Shorter','Same','\u224848 \u03bcs','\u22482 hours'], answer:2,
    why:'$\\Delta t=\\gamma\\Delta t_0=22\\times2.2\\approx48$ \u03bcs \u2014 letting cosmic-ray muons reach the ground.' },

  { id:'q-qm1', topic:'quantum', difficulty:'expert',
    q:"Heisenberg's uncertainty principle states:",
    choices:['All measurements are wrong','Position and momentum cannot BOTH be known precisely','Particles have no mass','Energy disappears'], answer:1,
    why:'$\\Delta x\\Delta p\\ge\\hbar/2$ \u2014 a fundamental wave property of nature, not clumsy instruments.' }
);
