/* PhysiX Academy — Quiz Bank Part B: Level 3 (Mechanics, Fluids, Thermo, Waves) */
'use strict';

QUIZ_BANK.push(
  { id:'q-un1', topic:'units', difficulty:'expert',
    q:'The dimensional formula of force is:',
    choices:['$MLT^{-1}$','$MLT^{-2}$','$ML^2T^{-2}$','$MLT^2$'], answer:1,
    why:'$F=ma$: mass $M$ \u00d7 acceleration $LT^{-2}$ gives $MLT^{-2}$.' },

  { id:'q-pr1', topic:'projectile', difficulty:'advanced',
    q:'A ball thrown horizontally from a cliff lands later than a dropped one?',
    choices:['Yes, it travels farther in time','Same time','No, sooner','Depends on mass'], answer:1,
    why:'Vertical motion is independent: both fall $h=\\tfrac12 gt^2$ from the same height.' },
  { id:'q-pr2', topic:'projectile', difficulty:'expert',
    q:'At the top of its arc, a projectile\u2019s acceleration is:',
    choices:['Zero','$g$ downward','Horizontal','$g$ upward'], answer:1,
    why:'Gravity never pauses; only the VERTICAL velocity is momentarily zero at apex.' },

  { id:'q-f5', topic:'friction', difficulty:'advanced',
    q:'A block slides down a rough incline at constant velocity. Net force on it is:',
    choices:['Downhill','Uphill','Zero','Equal to $\\mu mg$'], answer:2,
    why:'Constant velocity means equilibrium: gravity\u2019s downhill component exactly balances friction.' },
  { id:'q-f6', topic:'friction', difficulty:'expert',
    q:'Maximum speed on an unbanked curve of radius r with friction \u03bc is:',
    choices:['$\\sqrt{\\mu g r}$','$\\mu g r$','$\\sqrt{gr/\\mu}$','$2\\mu gr$'], answer:0,
    why:'Friction supplies centripetal force: $\\mu mg = mv^2/r$.' },

  { id:'q-e5', topic:'energy', difficulty:'advanced',
    q:'Work done by a spring returning to natural length equals:',
    choices:['$kx$','$\\tfrac12 kx^2$','$kx^2$','Zero'], answer:1,
    why:'Stored elastic energy $\\tfrac12 kx^2$ converts fully to kinetic work.' },
  { id:'q-e6', topic:'energy', difficulty:'expert',
    q:'For a variable force, work is found by:',
    choices:['$F \\times d$ only','Area under F\u2013x graph','Slope of F\u2013x graph','$F/d$'], answer:1,
    why:'Integration of F dx = area under the force\u2013displacement curve.' },

  { id:'q-cm1', topic:'com', difficulty:'intermediate',
    q:'Two 3 kg masses sit at x=0 and x=4 m. Centre of mass is at:',
    choices:['x=1 m','x=2 m','x=3 m','x=4 m'], answer:1,
    why:'Equal masses: COM midway at 2 m. Formula $x_{cm}=\\Sigma mx/\\Sigma m$.' },

  { id:'q-rot1', topic:'rotation', difficulty:'intermediate',
    q:'Rotational analogue of mass is:',
    choices:['Torque','Moment of inertia','Angular momentum','Radius'], answer:1,
    why:'$I=\\Sigma mr^2$ resists angular acceleration just as m resists linear.' },
  { id:'q-rot2', topic:'rotation', difficulty:'expert',
    q:'A skater pulls arms in and spins faster because:',
    choices:['Angular momentum must be conserved','Mass increases','Energy increases','Torque appears'], answer:0,
    why:'$I\\omega$ constant: shrinking I raises \u03c9. KE actually RISES (her muscles do work).' },

  { id:'q-g3', topic:'gravity', difficulty:'advanced',
    q:"Kepler's third law says $T^2 \\propto$:",
    choices:['$r$','$r^2$','$r^3$','$1/r$'], answer:2,
    why:'$T^2=\\tfrac{4\\pi^2}{GM}r^3$ \u2014 outer planets take disproportionately longer.' },
  { id:'q-g4', topic:'gravity', difficulty:'expert',
    q:'Escape velocity from a planet of mass M, radius R is $\\sqrt{2GM/R}$. Keeping R fixed but making M four times larger makes escape velocity:',
    choices:['Half','Same','Twice','Four times'], answer:2,
    why:'$v_{esc}\\propto\\sqrt{M}$: \u221a4 = 2. It never depends on the projectile\u2019s own mass.' },

  { id:'q-sol1', topic:'solids', difficulty:'advanced',
    q:"Hooke's law region on a stress\u2013strain graph shows:",
    choices:['A curve','A straight line through origin','A plateau','A vertical jump'], answer:1,
    why:'Stress \u221d strain until the proportional limit; slope is Young\u2019s modulus.' },

  { id:'q-fl1', topic:'fluids', difficulty:'beginner',
    q:'Archimedes\u2019 principle: buoyant force equals:',
    choices:["Object's weight","Weight of displaced fluid","Object's mass","Atmospheric pressure"], answer:1,
    why:'$F_b=\\rho_{fluid}gV_{disp}$ \u2014 the displaced fluid\u2019s weight.' },
  { id:'q-fl2', topic:'fluids', difficulty:'advanced',
    q:'Bernoulli: where fluid speed increases, pressure:',
    choices:['Increases','Decreases','Constant','Doubles'], answer:1,
    why:'Energy conservation along a streamline: fast regions are low-pressure (aircraft lift intuition).' },

  { id:'q-thp1', topic:'thermal', difficulty:'intermediate',
    q:'Latent heat during boiling goes into:',
    choices:['Raising temperature','Breaking intermolecular bonds','Expanding thermometer','Nothing'], answer:1,
    why:'Temperature stays at 100\u00b0C while energy separates molecules into vapour.' },

  { id:'q-th1', topic:'thermo', difficulty:'intermediate',
    q:'First law of thermodynamics is conservation of:',
    choices:['Momentum','Energy ($\\Delta U=Q-W$)','Entropy','Charge'], answer:1,
    why:'Internal energy changes only via heat added minus work done BY the system.' },
  { id:'q-th2', topic:'thermo', difficulty:'advanced',
    q:'A perfectly efficient heat engine (100%) would violate:',
    choices:['First law','Second law','Both','Neither'], answer:1,
    why:'Kelvin\u2013Planck statement forbids converting ALL heat to work; some must be exhausted.' },

  { id:'q-kt1', topic:'kinetic', difficulty:'advanced',
    q:'Average translational KE of gas molecules depends only on:',
    choices:['Pressure','Volume','Absolute temperature','Molar mass'], answer:2,
    why:'$\\langle E\\rangle=\\tfrac32 k_BT$ \u2014 temperature IS mean molecular kinetic energy.' },

  { id:'q-shm1', topic:'shm', difficulty:'intermediate',
    q:'In SHM, acceleration is proportional to:',
    choices:['Velocity','Displacement, oppositely directed','Time','Amplitude squared'], answer:1,
    why:'$a=-\\omega^2 x$: restoring pull grows with displacement, pointing back.' },
  { id:'q-shm2', topic:'shm', difficulty:'advanced',
    q:'Doubling the amplitude of a spring oscillator multiplies total energy by:',
    choices:['2','4','8','1'], answer:1,
    why:'$E=\\tfrac12 kA^2$ \u2014 energy scales as amplitude squared.' },

  { id:'q-wv3', topic:'waves', difficulty:'advanced',
    q:'Standing waves arise from:',
    choices:['Absorption','Interference of two opposite-travelling waves','Refraction','Doppler shift'], answer:1,
    why:'Identical waves moving opposite directions superpose into fixed nodes/antinodes.' },
  { id:'q-wv4', topic:'waves', difficulty:'expert',
    q:'A string fixed at both ends vibrates with fundamental f. Its second harmonic is:',
    choices:['f/2','1.5f','2f','4f'], answer:2,
    why:'Harmonics on fixed strings are integer multiples: $f_n=n f_1$.' },

  { id:'q-so1', topic:'sound', difficulty:'advanced',
    q:'An ambulance passing you: pitch sounds',
    choices:['Higher approaching, lower receding','Always higher','Always lower','Unchanged'], answer:0,
    why:'Doppler effect: wavefronts bunch ahead, spread behind.' },
  { id:'q-so2', topic:'sound', difficulty:'intermediate',
    q:'+10 dB means intensity multiplied by:',
    choices:['10','100','2','1000'], answer:0,
    why:'Decibels are logarithmic: every +10 dB is \u00d710 intensity.' }
);
